// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEOWQPaAr7X8_SzclI6MsiQJuphUH_84',
    appId: '1:719002664493:web:c87353fc73e84e426082a4',
    messagingSenderId: '719002664493',
    projectId: 'notesapp-dd35f',
    authDomain: 'notesapp-dd35f.firebaseapp.com',
    storageBucket: 'notesapp-dd35f.appspot.com',
    measurementId: 'G-GQC8WT8PTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZM0EFdplX91aFFy6yG1F1SUUOSIL6RJI',
    appId: '1:719002664493:android:09f6f419f427bf4e6082a4',
    messagingSenderId: '719002664493',
    projectId: 'notesapp-dd35f',
    storageBucket: 'notesapp-dd35f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4R6h-_FIdkIzStiTvZBvTNEArPymMkOQ',
    appId: '1:719002664493:ios:dbc632eaca0e82a46082a4',
    messagingSenderId: '719002664493',
    projectId: 'notesapp-dd35f',
    storageBucket: 'notesapp-dd35f.appspot.com',
    iosBundleId: 'com.example.notesappTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4R6h-_FIdkIzStiTvZBvTNEArPymMkOQ',
    appId: '1:719002664493:ios:97cfdd1f9aba1d2c6082a4',
    messagingSenderId: '719002664493',
    projectId: 'notesapp-dd35f',
    storageBucket: 'notesapp-dd35f.appspot.com',
    iosBundleId: 'com.example.notesappTask.RunnerTests',
  );
}
